typography_spectrum: 0.53953
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6875
  lightness: 0.3566216167528182
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Will Larson
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Design
    id: 10af3eea-be0d-433d-bf05-06bac4ec574c
    type: content
  - name: Design
    id: 7cfc3f09-be48-4633-9aff-54320091c10d
    type: content
favicon: null
title: Will Larson
description: 'High Concept, Low Brow'
purpose: []
