typography_spectrum: 0.20623601251281798
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.4088056997861713
  lightness: 0.6886126953177154
  saturation: 0.5458209172356874
  rhythmicContrast: 0.0875761981587857
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7869769057724625
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Will Larson
  email: William.Larson1@gmail.com
name: Will Larson
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Will Larson
description: 'High Concept, Low Brow'
purpose: []
