typography_spectrum: 0.20623601251281798
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.4088056997861713
  lightness: 0.6886126953177154
  saturation: 0.5458209172356874
  rhythmicContrast: 0.0875761981587857
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7869769057724625
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Will Larson
  email: William.Larson1@gmail.com
name: Will Larson
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Design
    id: 7cfc3f09-be48-4633-9aff-54320091c10d
    type: content
  - name: Photos
    id: 1fa43493-4eb5-49ff-8b76-c1a8fad6b016
    type: content
  - name: Photos
    id: 73d0b70e-2118-4f6a-be1e-402732870301
    type: content
favicon: null
title: Will Larson
description: 'High Concept, Low Brow'
purpose: []
